version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./src:/app/src
